[general]
import = [
  "~/.config/alacritty/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.normal]
family = "Fira Code Nerd Font Mono"

[scrolling]
history = 10000

[terminal]

[terminal.shell]
program = "zsh"
