set nocompatible

set autocomplete

set autoindent
set smartindent
set expandtab
set tabstop=4
set shiftwidth=4
set ignorecase
set smartcase
set hlsearch
set incsearch
set lazyredraw
set showmatch
set matchtime=2

set autoread
autocmd FocusGained,BufEnter * silent! checktime

set autowrite

set number
set relativenumber
set ruler
set scrolloff=7

set wildmenu
set wildoptions=pum
set wildignore=*.o,*~,*.pyc
set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store

set background=dark

set hidden

filetype off

filetype plugin indent on

syntax enable

colorscheme codedark

nnoremap <Space> <Nop>
let mapleader=" "

nmap <leader>w :w<CR>
nmap <c-s> :w<CR>
imap <c-s> <ESC>:w<CR>a

packadd nohlsearch
"packadd editorconfig
packadd comment
packadd hlyank

nnoremap <leader>e :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>

let g:airline_multiline = 1
let g:airline_powerline_fonts = 1
let g:NERDTreeShowHidden = 1

map <silent> ]w <Plug>CamelCaseMotion_w
map <silent> ]e <Plug>CamelCaseMotion_e
map <silent> [b <Plug>CamelCaseMotion_b
map <silent> [ge <Plug>CamelCaseMotion_ge
sunmap ]w
sunmap ]e
sunmap [b
sunmap [ge
